import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Khmer } from "next/font/google";
import "./globals.css";

// 1. Initialize all fonts with required subsets
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoKhmer = Noto_Sans_Khmer({
  variable: "--font-noto-khmer",
  subsets: ["khmer"],
  weight: ["400", "500", "700"], // Define weights needed for Khmer text
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2. Define proper TypeScript layout props
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html 
      lang="km" // Changed to 'km' for Khmer language accessibility
      className={`${geistSans.variable} ${geistMono.variable} ${notoKhmer.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-khmer">
        <nav className="bg-red-400">Navbar</nav>
        
        {/* The grow class ensures the main content fills the space, pushing the footer down */}
        <main className="grow">
          {children}
        </main>
        
        <footer className="bg-blue-400">Footer</footer>
      </body>
    </html>
  );
}

